### ISSUE TITLE
Move and Split topic not working

### ISSUE THREAD

**Issue by aronprins** [potsky/bbPress-Multilingual#3]
Hey!

Thanks for putting this on github.
I found a bug where it's impossible to move replies or split topics.

Any idea how to fix this?
Cheers,
Aron

**Comment by potsky** [comment]
Hi Aron,

the WPML is still buggy. I have these kinds of bugs too but they do not fix them. They ask me a SSH access to my server and they never answer to me. WPML is not really serious.

Sorry.
